ifdef CONFIG_KSU_DISABLE_MANAGER
ccflags-y += -DCONFIG_KSU_DISABLE_MANAGER
endif

ifdef CONFIG_KSU_DISABLE_POLICY
ccflags-y += -DCONFIG_KSU_DISABLE_POLICY
endif

ifdef CONFIG_KSU_DEBUG
ccflags-y += -DCONFIG_KSU_DEBUG
endif

ifdef CONFIG_KSU_TOOLKIT_SUPPORT
ccflags-y += -DCONFIG_KSU_TOOLKIT_SUPPORT
endif

ifdef CONFIG_KSU_MULTI_MANAGER_SUPPORT
ccflags-y += -DCONFIG_KSU_MULTI_MANAGER_SUPPORT
endif

# ddk are only support Tracepoint Syscall Redirect hook
ifdef CONFIG_KSU_TRACEPOINT_HOOK
ccflags-y += -DCONFIG_KSU_TRACEPOINT_HOOK
endif

CONFIG_KSU_FULL_NAME_FORMAT := "%TAG_NAME%-%COMMIT_SHA%@%REPO_NAME%"
